default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

development:
  <<: *default
  database: food_development

test:
  <<: *default
  database: food_test

production:
  <<: *default
  database: food_production
  host: localhost
  username: phuong3030
  password: <%= ENV['QUOTE_DATABASE_PASSWORD'] %>

cucumber:
  <<: *default
